<?php

/**
 * @file
 * Contains spotify_artists.module.
 */

/**
 * Implements hook_theme().
 */
function spotify_artists_theme() {

  return [
    'spotify_artists_block' => [
      'variables' => [
        'artists' => [],
      ],
    ],
    'spotify_artists_field' => [
      'variables' => [
        'artist' => NULL,
      ],
    ],
    'spotify_artists_page' => [
      'variables' => [
        'artist' => NULL,
      ],
    ],
  ];
}
